export const CURRENT_RUNNER_ID = 'runner-001';

export const mockRunnerProfile = {
  id: CURRENT_RUNNER_ID,
  full_name: 'Chidi Obi',
  profile_picture: '',
  phone: '+234 803 456 7890',
  email: 'chidi@sarunn.app',
  verified: true,
  campus: 'University of Lagos',
  assigned_zones: ['Yaba', 'Akoka', 'Surulere'],
  bank_name: 'Access Bank',
  account_number: '1234567890',
  account_name: 'Chidi Obi',
  total_deliveries: 247,
  rating: 4.9,
  earnings_total: 486500,
  earnings_week: 38400,
  earnings_month: 128500,
  account_status: 'active',
  suspension_reason: '',
  vehicle: 'Motorbike',
  plate_number: 'LAG-12AB-34',
};

export const mockAvailableRuns = [
  {
    id: 'run-1001',
    title: 'Campus lunch delivery',
    campus: 'University of Lagos',
    zone: 'Yaba',
    status: 'open',
    claimed_by: null,
    pickup: {
      vendor_name: 'Burger Palace',
      address: '14 Allen Ave, Ikeja',
      contact: '+234 801 555 2201',
      instructions: 'Ask for the blue package at the front desk.',
    },
    delivery: {
      customer_name: 'Adaeze Okafor',
      address: 'Hostel B, UNILAG',
      contact: '+234 803 900 2211',
    },
    payment_method: 'Cash on delivery',
    delivery_fee: 1800,
    estimated_distance_km: 6.4,
    special_instructions: 'Call customer on arrival.',
    customer: {
      name: 'Adaeze Okafor',
      phone: '+234 803 900 2211',
      email: 'adaeze@email.com',
    },
    vendor: {
      name: 'Burger Palace',
      phone: '+234 801 555 2201',
      email: 'orders@burgerpalace.ng',
    },
    timeline: [
      { label: 'Run created', at: '09:12' },
      { label: 'Waiting for runner', at: '09:14' },
    ],
    estimated_duration_min: 28,
  },
  {
    id: 'run-1002',
    title: 'Dinner grocery drop',
    campus: 'Lagos State University',
    zone: 'Surulere',
    status: 'claimed',
    claimed_by: CURRENT_RUNNER_ID,
    pickup: {
      vendor_name: 'Fresh Mart',
      address: '7 Victoria Island',
      contact: '+234 809 200 1100',
      instructions: 'Collect from the dispatch counter.',
    },
    delivery: {
      customer_name: 'Fatima Bello',
      address: 'Main Gate, LASU',
      contact: '+234 807 800 5555',
    },
    payment_method: 'Card',
    delivery_fee: 2400,
    estimated_distance_km: 9.1,
    special_instructions: 'Keep groceries upright.',
    customer: {
      name: 'Fatima Bello',
      phone: '+234 807 800 5555',
      email: 'fatima@email.com',
    },
    vendor: {
      name: 'Fresh Mart',
      phone: '+234 809 200 1100',
      email: 'hello@freshmart.ng',
    },
    timeline: [
      { label: 'Run created', at: '08:48' },
      { label: 'Claimed by Chidi Obi', at: '08:55' },
    ],
    estimated_duration_min: 35,
  },
  {
    id: 'run-1003',
    title: 'Library snack drop',
    campus: 'University of Lagos',
    zone: 'Akoka',
    status: 'open',
    claimed_by: null,
    pickup: {
      vendor_name: 'Campus Bites',
      address: '23 Herbert Macaulay Way',
      contact: '+234 806 123 7788',
      instructions: 'Pick up from the side window.',
    },
    delivery: {
      customer_name: 'Emeka Nwosu',
      address: 'Akoka Hall, UNILAG',
      contact: '+234 803 221 1100',
    },
    payment_method: 'Transfer',
    delivery_fee: 1500,
    estimated_distance_km: 4.2,
    special_instructions: 'No spicy sauce in the bag.',
    customer: {
      name: 'Emeka Nwosu',
      phone: '+234 803 221 1100',
      email: 'emeka@email.com',
    },
    vendor: {
      name: 'Campus Bites',
      phone: '+234 806 123 7788',
      email: 'orders@campusbites.ng',
    },
    timeline: [
      { label: 'Run created', at: '09:21' },
      { label: 'Ready for pickup', at: '09:25' },
    ],
    estimated_duration_min: 20,
  },
  {
    id: 'run-1004',
    title: 'Medical supply pickup',
    campus: 'Yaba College of Technology',
    zone: 'Yaba',
    status: 'open',
    claimed_by: null,
    pickup: {
      vendor_name: 'Care Pharmacy',
      address: '5 Commercial Ave, Yaba',
      contact: '+234 812 700 4400',
      instructions: 'Bring receipt to the pharmacist.',
    },
    delivery: {
      customer_name: 'Ngozi Adebayo',
      address: 'Main Campus, YABATECH',
      contact: '+234 810 123 7788',
    },
    payment_method: 'Cash on delivery',
    delivery_fee: 2100,
    estimated_distance_km: 5.8,
    special_instructions: 'Handle fragile package with care.',
    customer: {
      name: 'Ngozi Adebayo',
      phone: '+234 810 123 7788',
      email: 'ngozi@email.com',
    },
    vendor: {
      name: 'Care Pharmacy',
      phone: '+234 812 700 4400',
      email: 'support@carepharmacy.ng',
    },
    timeline: [
      { label: 'Run created', at: '09:33' },
      { label: 'Waiting for runner', at: '09:34' },
    ],
    estimated_duration_min: 25,
  },
];

export const mockAdminUsers = {
  runners: [
    {
      id: 'runner-001',
      full_name: 'Chidi Obi',
      profile_picture: '',
      email: 'chidi@sarunn.app',
      phone: '+234 803 456 7890',
      campus: 'University of Lagos',
      assigned_zones: ['Yaba', 'Akoka', 'Surulere'],
      bank_name: 'Access Bank',
      account_number: '1234567890',
      account_name: 'Chidi Obi',
      verification_status: 'verified',
      registration_date: '2026-03-12',
      documents_submitted: ['Government ID', 'Emergency contact', 'Bank details'],
      role: 'Runner',
      account_status: 'active',
      total_deliveries: 247,
      total_orders: 0,
      last_active: '2026-06-27',
      suspension_reason: '',
      rating: 4.9,
      approval_status: 'active',
      verified: true,
      suspended_at: '',
    },
    {
      id: 'runner-002',
      full_name: 'Amaka Eze',
      profile_picture: '',
      email: 'amaka@sarunn.app',
      phone: '+234 801 234 5678',
      campus: 'Lagos State University',
      assigned_zones: ['Ojo', 'Iba'],
      bank_name: 'GTBank',
      account_number: '0987654321',
      account_name: 'Amaka Eze',
      verification_status: 'pending',
      registration_date: '2026-06-21',
      documents_submitted: ['Government ID', 'Profile picture', 'Bank details'],
      role: 'Runner',
      account_status: 'pending approval',
      total_deliveries: 0,
      total_orders: 0,
      last_active: '2026-06-24',
      suspension_reason: '',
      rating: 0,
      approval_status: 'pending',
      verified: false,
      suspended_at: '',
    },
  ],
  vendors: [
    {
      id: 'vendor-001',
      business_name: 'Burger Palace',
      profile_picture: '',
      owner_name: 'Olu Ade',
      email: 'hello@burgerpalace.ng',
      phone: '+234 801 555 2201',
      business_address: '14 Allen Ave, Ikeja',
      government_id: 'National ID',
      bank_name: 'Access Bank',
      account_number: '1122334455',
      account_name: 'Burger Palace Ltd',
      campus: 'University of Lagos',
      cac_number: 'CAC/2026/001',
      verification_status: 'verified',
      registration_date: '2026-01-18',
      documents_submitted: ['Logo', 'Government ID', 'Bank details', 'CAC certificate'],
      role: 'Vendor',
      account_status: 'active',
      total_deliveries: 312,
      total_orders: 312,
      last_active: '2026-06-27',
      suspension_reason: '',
      rating: 4.8,
      approval_status: 'active',
      verified: true,
      suspended_at: '',
    },
    {
      id: 'vendor-002',
      business_name: 'Campus Bites',
      profile_picture: '',
      owner_name: 'Sade Bello',
      email: 'orders@campusbites.ng',
      phone: '+234 806 123 7788',
      business_address: '23 Herbert Macaulay Way',
      government_id: 'Driver License',
      bank_name: 'Zenith Bank',
      account_number: '2233445566',
      account_name: 'Campus Bites',
      campus: 'University of Lagos',
      cac_number: '',
      verification_status: 'pending',
      registration_date: '2026-06-20',
      documents_submitted: ['Profile picture/logo', 'Government ID', 'Bank details'],
      role: 'Vendor',
      account_status: 'suspended',
      total_deliveries: 78,
      total_orders: 78,
      last_active: '2026-06-25',
      suspension_reason: 'Pending document verification',
      rating: 4.4,
      approval_status: 'suspended',
      verified: false,
      suspended_at: '2026-06-25',
    },
  ],
  customers: [
    {
      id: 'customer-001',
      full_name: 'Adaeze Okafor',
      profile_picture: '',
      email: 'adaeze@email.com',
      phone: '+234 803 900 2211',
      campus: 'University of Lagos',
      verification_status: 'verified',
      registration_date: '2026-02-11',
      documents_submitted: ['Profile picture'],
      role: 'Customer',
      account_status: 'active',
      total_deliveries: 23,
      total_orders: 23,
      last_active: '2026-06-27',
      suspension_reason: '',
      rating: 4.8,
      approval_status: 'active',
      verified: true,
      suspended_at: '',
      bank_name: 'N/A',
      account_number: 'N/A',
      account_name: 'N/A',
    },
  ],
};

export const mockPaymentDashboard = {
  revenue: 1284500,
  pending_payouts: 286400,
  completed_payouts: 915300,
  runner_earnings: 365500,
  vendor_settlements: 562400,
  analytics: [
    { label: 'Orders settled', value: 124, change: '+11%' },
    { label: 'Average payout delay', value: '18 min', change: '-4 min' },
    { label: 'Refund rate', value: '1.8%', change: '-0.2%' },
    { label: 'Withdrawal approvals', value: '96%', change: '+2%' },
  ],
  transaction_history: [
    { id: 'TX-4521', title: 'Platform fee from Order #4521', amount: 5300, type: 'credit', status: 'settled', date: '2026-06-27' },
    { id: 'TX-4520', title: 'Runner payout - Chidi Obi', amount: 12400, type: 'debit', status: 'paid', date: '2026-06-27' },
    { id: 'TX-4519', title: 'Vendor settlement - Burger Palace', amount: 48600, type: 'debit', status: 'pending', date: '2026-06-26' },
    { id: 'TX-4518', title: 'Platform fee from Order #4518', amount: 4200, type: 'credit', status: 'settled', date: '2026-06-26' },
  ],
  refund_history: [
    { id: 'RF-1001', title: 'Refund for Order #4490', amount: 3200, status: 'processed', date: '2026-06-25' },
    { id: 'RF-1002', title: 'Refund for Order #4485', amount: 1800, status: 'pending', date: '2026-06-24' },
  ],
  withdrawal_requests: [
    { id: 'WD-2001', title: 'Chidi Obi', amount: 12400, status: 'approved', date: '2026-06-27', method: 'Bank transfer' },
    { id: 'WD-2002', title: 'Campus Bites', amount: 32400, status: 'pending', date: '2026-06-26', method: 'Bank transfer' },
    { id: 'WD-2003', title: 'Tunde Adeyemi', amount: 15200, status: 'review', date: '2026-06-25', method: 'Wallet payout' },
  ],
};

export function getAdminUsersByRole(role) {
  return mockAdminUsers[role] || [];
}

export function getAdminUserById(role, id) {
  return getAdminUsersByRole(role).find((user) => user.id === id);
}

export function getRunById(id, fallbackRuns = mockAvailableRuns) {
  return fallbackRuns.find((run) => run.id === id);
}
